### ISSUE TITLE
androidx.recyclerview.widget.RecyclerView.canScrollVertically(int)' on a null object reference

### ISSUE THREAD

**Issue by SNXJ** [zhpanvip/BannerViewPager#108]
使用BannerViewPager 3.0.0 测试发现部分 魅族 系统7.x 小米系统8.x  华为报以下错误：

Build: HONOR/PCT-AL10/HWPCT:9/HUAWEIPCT-AL10/143C00R2:user/release-keys

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.recyclerview.widget.RecyclerView.canScrollVertically(int)' on a null object reference
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10378)
	at androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl.onInitializeAccessibilityNodeInfo(ViewPager2.java:1017)
	at com.zhpan.bannerview.provider.ProxyLayoutManger.onInitializeAccessibilityNodeInfo(ProxyLayoutManger.java:94)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10348)
	at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:74)
	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:86)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:7758)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:7719)
	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:27508)
	at android.view.View.createAccessibilityNodeInfo(View.java:7702)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1147)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1170)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1170)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1170)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1170)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:972)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:336)
	at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:67)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1324)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
-mainthread -loghandler

**Comment by zhpanvip** [comment]
是否开启了混淆？检查下是不是添加了混淆规则。

**Comment by SNXJ** [comment]
> 是否开启了混淆？检查下是不是添加了混淆规则。

没有开启混淆   是必须开启混淆吗？

**Comment by zhpanvip** [comment]
如果开了混淆没添加混淆配置是会有问题的。我现在有魅族7.0和华为的测试机，没有出现过异常。你想尝试注释掉setScrollDuration方法看下还会有问题。

**Comment by zhpanvip** [comment]
如果去掉setScrollDuration没问题麻烦回复一下。我先把这个issue置顶。

**Comment by SNXJ** [comment]
> 如果去掉setScrollDuration没问题麻烦回复一下。我先把这个issue置顶。

去掉setScrollDuration是可以的

**Comment by zhpanvip** [comment]
好的，感谢。

**Comment by SNXJ** [comment]
> 好的，感谢。

不不不     应该是谢谢你  issues回复这么快  辛苦了

**Comment by zhpanvip** [comment]
最新发布的3.0.1尝试修复了这个bug.你可以升级版本再次尝试。但是我觉得为了线上安全setScrollDuration这个方法还是要谨慎使用。可以加下reaeme上的qq群，如果有问题可以及时反馈。

**Comment by SNXJ** [comment]
> 最新发布的3.0.1尝试修复了这个bug.你可以升级版本再次尝试。但是我觉得为了线上安全setScrollDuration这个方法还是要谨慎使用。可以加下readme上的qq群，如果有问题可以及时反馈。

好的  有VX群吗

**Comment by zhpanvip** [comment]
> 好的 有VX群吗
暂时没有建vx群，vx群二维码有期限限制没有qq群方便。

**Comment by zhpanvip** [comment]
Fixed in v3.0.1
