### ISSUE TITLE
IllegalStateException: Page can only be offset by a positive amount, not by-940

### ISSUE THREAD

**Issue by luodongwen** [zhpanvip/BannerViewPager#148]
java.lang.IllegalStateException: Page can only be offset by a positive amount, not by -940
        at androidx.viewpager2.widget.ScrollEventAdapter.updateScrollEventValues(ScrollEventAdapter.java:280)
        at androidx.viewpager2.widget.ScrollEventAdapter.onScrolled(ScrollEventAdapter.java:178)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5183)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5348)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1132)
        at android.view.Choreographer.doCallbacks(Choreographer.java:943)
        at android.view.Choreographer.doFrame(Choreographer.java:850)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1118)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7012)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)

  <com.scwang.smart.refresh.layout.SmartRefreshLayout
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_classify_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginTop="@dimen/core_spa_small" />
        </com.scwang.smart.refresh.layout.SmartRefreshLayout>
Banner addHeader 的时候报错。BaseRecyclerViewAdapterHelper
2.6.6没事

**Comment by zhpanvip** [comment]
改成用代码设置revealWidth，下个版本会修复。

**Comment by luodongwen** [comment]
代码设置revealWidth是啥。没看懂

**Comment by zhpanvip** [comment]
> 代码设置revealWidth是啥。没看懂

你是不是设置了一屏三页样式了？

**Comment by peter100u** [comment]
没搞懂，什么是revealWidth, 怎么解决 ？麻烦说下原因

**Comment by peter100u** [comment]
> 

麻烦说下原因，我遇到类似问题，但是无法重现
