### ISSUE TITLE
java.lang.RuntimeException: view must have a tag

### ISSUE THREAD

**Issue by Fanyunf** [zhpanvip/BannerViewPager#201]
来回滑动会报这个错

**Comment by zhpanvip** [comment]
可以贴下详细日志吗

**Comment by Fanyunf** [comment]
java.lang.RuntimeException: view must have a tag
        at .DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:109)
        at androidx.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:74)
        at androidx.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
        at androidx.databinding.ViewDataBinding.bind(ViewDataBinding.java:695)
        at .databinding.ItemSlideModeBinding.bind(ItemSlideModeBinding.java:87)
        at .databinding.ItemSlideModeBinding.bind(ItemSlideModeBinding.java:75)
        at .ui.adapter.ViewBindingSampleAdapter.bindData(ViewBindingSampleAdapter.kt:24)
        at .ui.adapter.ViewBindingSampleAdapter.bindData(ViewBindingSampleAdapter.kt:15)

**Comment by Fanyunf** [comment]
mViewPager.setIndicatorSlideMode(IndicatorSlideMode.SMOOTH)
            .setIndicatorSliderColor(R.color.cl_A3.asResColor(), R.color.blue_D5.asResColor())
            .setIndicatorSliderRadius(resources.getDimensionPixelOffset(R.dimen.dp_4), resources.getDimensionPixelOffset(R.dimen.pd5))
            .setIndicatorView(indicator_view)
            .setLifecycleRegistry(lifecycle)
            .setRoundCorner(BannerUtils.dp2px(6f))
            .setOnPageClickListener(this::pageClick)
            .setAdapter(ViewBindingSampleAdapter(this))
            .setPageMargin(resources.getDimensionPixelOffset(R.dimen.pd15))
            .setRevealWidth(resources.getDimensionPixelOffset(R.dimen.dp_10))
            .setPageStyle(PageStyle.MULTI_PAGE_SCALE)
            .setAutoPlay(false)
            .create()

mViewPager.refreshData(noticeList)
这里是使用

**Comment by Fanyunf** [comment]
解决了

**Comment by xiaoxing1992** [comment]
> 解决了

怎么解决的  求助一下

**Comment by lindroy** [comment]
用ViewBinding时遇到了这个问题。
