### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by ximenchuipaopao** [zhpanvip/BannerViewPager#327]
java.lang.RuntimeException: Canvas: trying to draw too large(242851840bytes) bitmap.
                             	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
                             	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
                             	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
                             	at android.widget.ImageView.onDraw(ImageView.java:1360)
                             	at android.view.View.draw(View.java:20221)
                             	at android.view.View.updateDisplayListIfDirty(View.java:19096)
                             	at android.view.View.draw(View.java:19949)
                             	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                             	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                             	at android.view.View.updateDisplayListIfDirty(View.java:19087)
                             	at android.view.View.draw(View.java:19949)
                             	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                             	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
                             	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                             	at android.view.View.draw(View.java:20224)
                             	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
                             	at android.view.View.updateDisplayListIfDirty(View.java:19096)
                             	at android.view.View.draw(View.java:19949)
                             	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                             	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                             	at android.view.View.updateDisplayListIfDirty(View.java:19087)
                             	at android.view.View.draw(View.java:19949)
                             	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                             	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                             	at com.zhpan.bannerview.BannerViewPager.dispatchDraw(BannerViewPager.java:387)

**Comment by zhpanvip** [comment]
是你自己 Item 里 View 的问题，排查一下你的代码。
