### ISSUE TITLE
The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!

### ISSUE THREAD

**Issue by Flywith24** [zhpanvip/BannerViewPager#43]
版本：2.4.2

网络请求获取数据，使用`void create(List<T> list)`更换数据源

程序崩溃（仅出现一次）

```
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 5, found: 0 Pager id: cn.example.market:id/vp_main Pager class: class com.zhpan.bannerview.view.CatchViewPager Problematic adapter: class com.zhpan.bannerview.adapter.BannerPagerAdapter
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1143)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:910)
        at android.view.Choreographer.doCallbacks(Choreographer.java:712)
        at android.view.Choreographer.doFrame(Choreographer.java:643)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:896)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6379)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

根据源码发现`create`方法每次都是创建新的adapter的，所以这个异常有点奇怪。各位有什么想法吗？

**Comment by zhpanvip** [comment]
应该是返回的数据为0的时可能会出现这个问题，其实跟 #41 这个一样的bug，下个版本修复。

**Comment by zhpanvip** [comment]
建议你升级到2.5.0版本，虽然2.5.0刷新时返回0也会报错。。这个问题要在2.5.1修复了。

**Comment by Flywith24** [comment]
> 建议你升级到2.5.0版本，虽然2.5.0刷新时返回0也会报错。。这个问题要在2.5.1修复了。

好的，感谢您的回复。

**Comment by zhpanvip** [comment]
2.5.1 released
